version: "3.9"
services:
  order-service:
    container_name: order_container
    build:
        context: OrderService
    image: tesodev/order_service
    ports:
      - "8087:8087"
    depends_on:
      - mongo-db
      - customer-service
    networks:
      service-network:
        aliases:
          - order-service

  customer-service:
    container_name: customer_container
    build:
      context: CustomerService
    image: tesodev/customer_service
    ports:
      - "8086:8086"
    depends_on:
      - mongo-db
    networks:
      service-network:
        aliases:
          - CustomerService
    restart: on-failure

  mongo-db:
    image: mongo
    ports:
        - "27017:27017"
    container_name: mongo_container
    volumes:
      - mongo-data:/data/db
    networks:
      service-network:
        aliases:
          - mongo-db

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_service_container
    ports:
      - "8080:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    networks:
      service-network:
        aliases:
          - swagger-ui
    environment:
      URLS: "[{ url: \"doc/customer_swagger.yaml\", name: \"Customers\" }, { url: \"doc/order_swagger.yaml\", name: \"Orders\" }, ]"

volumes:
  mongo-data:

networks:
  service-network:

    # { url: \"doc/matching_swagger.yaml\", name: \"Matching\" }]