openapi: 3.0.0
info:
  title: API documentation
  version: 1.0.0
  schemes:
    - http
servers:
  - url: http://localhost:8086
tags:
  - name: Customers
paths:
  /customer/get/customerId/{customerId}:
    $ref: './resources/customer.yaml#/getCustomerByID'   
  /customer/bulk:
    $ref: './resources/customer.yaml#/getCustomers' 
  /customer/insert:
    $ref: './resources/customer.yaml#/createCustomer'   
  /customer/delete/customerId/{customerId}:
    $ref: './resources/customer.yaml#/deleteCustomer'   
  /customer/update/customerId/{customerId}:
    $ref: './resources/customer.yaml#/updateCustomer' 
  /customer/validate/customerId/{customerId}:
    $ref: './resources/customer.yaml#/validateCustomer' 
