openapi: 3.0.0
info:
  title: API documentation
  version: 1.0.0
  schemes:
    - http
servers:
  - url: http://localhost:8087
tags:
  - name: Orders
paths:
  /order/insert/customerId/{customerId}:
    $ref: './resources/order.yaml#/insertOrder'   

  /order/update/orderId/{orderId}:
    $ref: './resources/order.yaml#/updateOrder'   

  /order/delete/orderId/{orderId}:
    $ref: './resources/order.yaml#/deleteOrder'   

  /order/bulk:
    $ref: './resources/order.yaml#/getOrders'
       
  /order/bulk/customer/customerId/{customerId}:
    $ref: './resources/order.yaml#/getOrdersByCustomerId'   

  /order/get/orderId/{orderId}:
    $ref: './resources/order.yaml#/getOrderById'   

  /order/update/status/orderId/{orderId}:
    $ref: './resources/order.yaml#/changeOrderStatus'   
